# Generated by Django 4.2.30 on 2026-09-24 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número de semestre')),
                ('horas_totales', models.IntegerField(verbose_name='Horas totales del semestre')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'db_table': 'semestre',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la asignatura')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('creditos', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Créditos')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaturas', to='malla.semestre')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'db_table': 'asignatura',
                'ordering': ['semestre', 'codigo'],
            },
        ),
    ]
