# Generated by Django 4.2.30 on 2026-09-24 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('malla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('anio_egreso', models.IntegerField(verbose_name='Año de egreso')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiante',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Calificación')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='malla.asignatura')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='egreso.estudiante')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'nota',
                'ordering': ['estudiante', 'asignatura'],
            },
        ),
        migrations.CreateModel(
            name='CampoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=150, verbose_name='Empresa')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campos_laborales', to='egreso.estudiante')),
            ],
            options={
                'verbose_name': 'Campo Laboral',
                'verbose_name_plural': 'Campos Laborales',
                'db_table': 'campo_laboral',
                'ordering': ['empresa'],
            },
        ),
    ]
