# Generated by Django 4.2.30 on 2026-09-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egreso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la competencia')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
                'db_table': 'competencia',
                'ordering': ['nombre'],
            },
        ),
    ]
